source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KCKeyboardScrollingImagePicker_Example', :exclusive => true do
    pod 'KCKeyboardScrollingImagePicker', :path => '../'
    pod 'PureLayout'
    pod 'JSQMessagesViewController'
end

target 'KCKeyboardScrollingImagePicker_Tests', :exclusive => true do
    pod 'KCKeyboardScrollingImagePicker', :path => '../'
end