source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KCKeyboardImagePicker_Example', :exclusive => true do
    pod 'KCKeyboardImagePicker', :path => '../'
    pod 'JSQMessagesViewController'
end

target 'KCKeyboardImagePicker_Tests', :exclusive => true do
    pod 'KCKeyboardImagePicker', :path => '../'
end